# Generated by Django 5.2.7 on 2025-11-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messagereaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageReaction',
        ),
    ]
