# Generated by Django 5.2.7 on 2025-11-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='index_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='processing_status',
            field=models.CharField(choices=[('READY', 'Ready'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
