# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_workspaceinvitation_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceinvitation',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When the invitation was accepted or declined', null=True),
        ),
    ]

