# Generated by Django 5.2.7 on 2025-11-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_workspaceinvitation_responded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INVITATION', 'Invitation'), ('ROLE_CHANGED', 'Role Changed'), ('MEMBER_ADDED', 'Member Added'), ('WORKSPACE_DELETED', 'Workspace Deleted')], max_length=20),
        ),
    ]
