# Generated by Django 5.2.7 on 2025-11-23 16:51

import workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=200, validators=[workspaces.models.validate_workspace_name]),
        ),
    ]
