"""
Django settings for genscholar project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# my_project/settings.py
import os
from dotenv import load_dotenv
from pathlib import Path

if os.getenv("RAILWAY_GIT_COMMIT_SHA") is None:
    load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-f0-e%8**&h%51ef5k+!e3a7$^!q_0zu1p=pdihv6t=yk!3#h#v')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '').strip()
is_railway = bool(os.getenv('RAILWAY_ENVIRONMENT') or os.getenv('RAILWAY_GIT_COMMIT_SHA'))

if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'testserver']
    if is_railway:
        railway_public_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN', '').strip()
        if railway_public_domain:
            ALLOWED_HOSTS.append(railway_public_domain)
        if not DEBUG and not railway_public_domain:
            ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    'corsheaders',
    'channels',
    'accounts',
    'workspaces',
    'pdfs',
    'chat',
    'chatbot',
    'threads',  # Threaded discussions on PDF text selections
    'notifications',

    'background_task',
    
    # django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'genscholar.middleware.ApiCsrfExemptMiddleware',  # Custom: exempts /api/ routes from CSRF
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'genscholar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'genscholar.wsgi.application'

# Channels configuration
ASGI_APPLICATION = 'genscholar.asgi.application'

# --- Channel Layer Configuration ---
# This allows your HTTP views to talk to your WebSocket consumers
# Try Redis first, fallback to in-memory for development
REDIS_AVAILABLE = os.getenv('REDIS_AVAILABLE', 'true').lower() == 'true'

if REDIS_AVAILABLE:
    try:
        import redis
        from urllib.parse import urlparse
        
        # Try to get Redis URL from environment (Railway provides REDIS_URL or REDIS_PUBLIC_URL)
        redis_url = os.getenv('REDIS_URL') or os.getenv('REDIS_PUBLIC_URL')
        
        if redis_url:
            # Parse Redis URL: redis://username:password@host:port
            parsed = urlparse(redis_url)
            redis_host = parsed.hostname
            redis_port = parsed.port or 6379
            redis_password = parsed.password
            redis_username = parsed.username or 'default'
            
            # Test connection with parsed credentials
            if redis_password:
                r = redis.Redis(
                    host=redis_host,
                    port=redis_port,
                    password=redis_password,
                    username=redis_username,
                    decode_responses=False
                )
            else:
                r = redis.Redis(
                    host=redis_host,
                    port=redis_port,
                    decode_responses=False
                )
            r.ping()  # Test connection
            
            # Configure channels_redis with the parsed URL
            if redis_password:
                # Use URL format for channels_redis
                CHANNEL_LAYERS = {
                    "default": {
                        "BACKEND": "channels_redis.core.RedisChannelLayer",
                        "CONFIG": {
                            "hosts": [redis_url],
                        },
                    },
                }
            else:
                CHANNEL_LAYERS = {
                    "default": {
                        "BACKEND": "channels_redis.core.RedisChannelLayer",
                        "CONFIG": {
                            "hosts": [(redis_host, redis_port)],
                        },
                    },
                }
        else:
            # Fallback to individual environment variables
            redis_host = os.getenv('REDISHOST', '127.0.0.1')
            redis_port = int(os.getenv('REDISPORT', '6379'))
            redis_password = os.getenv('REDISPASSWORD')
            redis_username = os.getenv('REDISUSER')
            
            # Test connection
            if redis_password:
                r = redis.Redis(
                    host=redis_host,
                    port=redis_port,
                    password=redis_password,
                    username=redis_username,
                    decode_responses=False
                )
            else:
                r = redis.Redis(
                    host=redis_host,
                    port=redis_port,
                    decode_responses=False
                )
            r.ping()  # Test connection
            
            # Configure channels_redis
            if redis_password and redis_username:
                redis_url_fallback = f"redis://{redis_username}:{redis_password}@{redis_host}:{redis_port}"
                CHANNEL_LAYERS = {
                    "default": {
                        "BACKEND": "channels_redis.core.RedisChannelLayer",
                        "CONFIG": {
                            "hosts": [redis_url_fallback],
                        },
                    },
                }
            else:
                CHANNEL_LAYERS = {
                    "default": {
                        "BACKEND": "channels_redis.core.RedisChannelLayer",
                        "CONFIG": {
                            "hosts": [(redis_host, redis_port)],
                        },
                    },
                }
    except ImportError:
        # Redis module not installed - use in-memory fallback
        print("WARNING: Redis module not installed. Using in-memory channel layer (not suitable for production).")
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels.layers.InMemoryChannelLayer"
            }
        }
    except Exception as e:
        # Redis connection failed - use in-memory fallback
        print(f"WARNING: Redis not available. Using in-memory channel layer (not suitable for production). Error: {e}")
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels.layers.InMemoryChannelLayer"
            }
        }
else:
    # Explicitly use in-memory for development
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# Try DATABASE_URL first (Railway provides this), then fall back to individual POSTGRES_* vars
database_url = os.getenv('DATABASE_URL', '')
if database_url:
    DATABASES = {
        'default': dj_database_url.parse(database_url)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB'),
            'USER': os.environ.get('POSTGRES_USER'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'pdfs' / 'static',
]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Authentication backends - allow login with username OR email
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default backend (username)
    'accounts.auth_backends.UsernameOrEmailBackend',  # Custom backend (username or email)
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth backend
]

# Site ID required for allauth
SITE_ID = 1

# django-allauth configuration
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = False
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300
LOGIN_REDIRECT_URL = 'dashboard'
ACCOUNT_LOGOUT_REDIRECT_URL = 'login'

# Social account providers configuration
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        }
    }
}

# Email configuration (read from environment variables)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'

# Set DEFAULT_FROM_EMAIL - use Gmail address if Gmail is configured, otherwise use env or fallback
default_from_env = os.getenv('DEFAULT_FROM_EMAIL', '')
if default_from_env and '@localhost' not in default_from_env:
    DEFAULT_FROM_EMAIL = default_from_env
elif EMAIL_HOST == 'smtp.gmail.com' and EMAIL_HOST_USER and '@gmail.com' in EMAIL_HOST_USER:
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
elif EMAIL_HOST_USER and '@' in EMAIL_HOST_USER and '@localhost' not in EMAIL_HOST_USER:
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    DEFAULT_FROM_EMAIL = 'noreply@genscholar.com'

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# CORS configuration for frontend API integration
cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '').strip()
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in (cors_origins_env if cors_origins_env else 'http://localhost:5173,https://genscholar.netlify.app').split(',') if origin.strip()]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_HEADERS = True
CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "OPTIONS",
    "PUT",
    "PATCH",
    "DELETE",
]

# CSRF configuration for frontend API integration
csrf_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS', '').strip()
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in (csrf_origins_env if csrf_origins_env else 'http://localhost:5173,https://genscholar.netlify.app').split(',') if origin.strip()]

# CSRF Cookie Settings
# httponly=False is required so JavaScript can read the CSRF token from cookies
# Cross-site cookies for production (HTTPS required)
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF tokens (default)

# Session Cookie Settings (for cross-origin authentication)
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True

try:
    from .railway import *  # noqa
except ImportError:
    pass  
