# Generated by Django 5.2.7 on 2025-11-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0002_pdffile_index_path_pdffile_processing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='index_path',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='processing_status',
        ),
        migrations.AddField(
            model_name='pdffile',
            name='is_indexed',
            field=models.BooleanField(default=False),
        ),
    ]
