# Generated by Django 5.2.8 on 2025-11-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='is_indexed',
            field=models.BooleanField(default=False),
        ),
    ]
